// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5E5YoJp9FDnSQlrT_LvRpS1Xh0MMOtPc',
    appId: '1:341374582141:web:7c3494882e16849e75e014',
    messagingSenderId: '341374582141',
    projectId: 'iiotmhi',
    authDomain: 'iiotmhi.firebaseapp.com',
    databaseURL: 'https://iiotmhi-default-rtdb.firebaseio.com',
    storageBucket: 'iiotmhi.appspot.com',
    measurementId: 'G-T0NXJR9D0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI7Yn-WoM6yQ2wf1EqKOJ4YEoHl27pwxk',
    appId: '1:341374582141:android:b384f8f8dd2530bd75e014',
    messagingSenderId: '341374582141',
    projectId: 'iiotmhi',
    databaseURL: 'https://iiotmhi-default-rtdb.firebaseio.com',
    storageBucket: 'iiotmhi.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5E5YoJp9FDnSQlrT_LvRpS1Xh0MMOtPc',
    appId: '1:341374582141:web:b9f0710eed9cfbdf75e014',
    messagingSenderId: '341374582141',
    projectId: 'iiotmhi',
    authDomain: 'iiotmhi.firebaseapp.com',
    databaseURL: 'https://iiotmhi-default-rtdb.firebaseio.com',
    storageBucket: 'iiotmhi.appspot.com',
    measurementId: 'G-EV7NC30VYE',
  );

}